[build]
  base = "."
  publish = "build/"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200

  [functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions/"